# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pow}
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Corey Johnson"]
  s.date = %q{2010-03-25}
  s.description = %q{Manipulating files and directories in Ruby is boring and tedious -- it's missing POW! Pow treats files and directories as ruby objects giving you more power and flexibility.}
  s.email = %q{probablycorey@gmail.com}
  s.extra_rdoc_files = [
    "README.txt",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     "License.txt",
     "Manifest.txt",
     "README.txt",
     "Rakefile",
     "TODO",
     "VERSION",
     "lib/pow.rb",
     "lib/pow/directory.rb",
     "lib/pow/file.rb",
     "lib/pow/pow.rb",
     "pow.gemspec",
     "spec/directory_spec.rb",
     "spec/file_spec.rb",
     "spec/pow_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/probablycorey/pow}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Easy file and directory handling}
  s.test_files = [
    "spec/directory_spec.rb",
     "spec/file_spec.rb",
     "spec/pow_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

